### ISSUE TITLE
Cannot automatically connect to the wireless network when the robot is powered on

### ISSUE THREAD

**Issue by WshgL** [ridgeback/ridgeback_robot#24]
Hello developers,

I'm troubled by the WIFI connection problem. 
The ridgeback can not automatically connect to the wireless network when the robot is powered on.

I get the following message when powering on the ridgeback:
```bash
[FAILED]"Failed to start LSB: IPv4 DHCP client with IPv4LL support" 
[FAILED]"Failed to start Raise network interfaces" 
[FAILED]"Failed to start Bluetooth service" 
[DEPEND]"Dependency failed for ds4drv daemon"
```
Please refer to the picture linked below
[photo_1](https://user-images.githubusercontent.com/43674763/50223821-2aa7c200-03d7-11e9-8b54-541e434bc6fa.jpg),  [photo_2](https://user-images.githubusercontent.com/43674763/50223823-2bd8ef00-03d7-11e9-8cc3-6182fd5ddb53.jpg),  [photo_3](https://user-images.githubusercontent.com/43674763/50223824-2d0a1c00-03d7-11e9-999a-a2c3ccbb1666.jpg),  [photo_4](https://user-images.githubusercontent.com/43674763/50223829-2ed3df80-03d7-11e9-80f5-67099913da37.jpg)

I try to use `connman` to connect wifi. But when I execute `scan wifi`, I get an error message `Error /net/connman/technology/wifi: No carrier`. By enabling and disabling the wifi device multiple times, this error message can be eliminated and the wifi can be connected normally.
Please refer to the picture linked below
[screen_shot_1](https://user-images.githubusercontent.com/43674763/50223977-925e0d00-03d7-11e9-984c-b35bab675bcc.png)

After trying the `connman` tool, I am trying to use `wicd-curses`. When I press C to connect my wireless network, the `ridgeback_node` suddenly died, I get the following error messages from `ridgeback_node`:
```bash
[ WARN] [1545225692.535805976]: Unknown error returned during write operation: system:22
[ERROR] [1545225692.715415235]: Error reading from socketcan: 19
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Cannot assign requested address
[ridgeback_node-4] process has died [pid 4277, exit code -6, cmd /home/administrator/ridgeback_ws/devel/lib/ridgeback_base/ridgeback_node __name:=ridgeback_node __log:=/home/administrator/.ros/log/d42872a8-0390-11e9-8181-000baba9f6ab/ridgeback_node-4.log].
log file: /home/administrator/.ros/log/d42872a8-0390-11e9-8181-000baba9f6ab/ridgeback_node-4*.log
```
Please refer to the picture linked below
[screen_shot_2](https://user-images.githubusercontent.com/43674763/50224227-49f31f00-03d8-11e9-82ea-97c39ffcdd15.png),  [screen_shot_3](https://user-images.githubusercontent.com/43674763/50224229-4bbce280-03d8-11e9-99ee-d7be685141f2.png)

In addition, I run `ifconfig` and get following message:
```bash
wlp2s0    Link encap:Ethernet  HWaddr ac:fd:ce:13:80:0d  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
Please refer to the picture linked below
[screen_shot_4](https://user-images.githubusercontent.com/43674763/50224318-92aad800-03d8-11e9-946b-a69810fc2028.png)

Look forward to your reply, thank you very much!

Best regards, 
Wilson

**Comment by tonybaltovski** [comment]
Hi,

Can you post the full output of `ifconfig`?  For Kinetic, `wicd-curses` should be used and `connman` should not be installed to avoid issues.

**Comment by WshgL** [comment]
@tonybaltovski 

I have completely removed `connman` using `sudo apt-get remove --purge connman`

`ifconfig` message as below:

```bash
br0       Link encap:Ethernet  HWaddr 00:0b:ab:a9:f6:ab  
          inet addr:192.168.131.1  Bcast:192.168.131.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:542215 errors:0 dropped:0 overruns:0 frame:0
          TX packets:248220 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:168148860 (168.1 MB)  TX bytes:192299507 (192.2 MB)

br0:0     Link encap:Ethernet  HWaddr 00:0b:ab:a9:f6:ab  
          inet addr:192.168.0.6  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

can0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          UP RUNNING NOARP  MTU:16  Metric:1
          RX packets:274411 errors:0 dropped:0 overruns:0 frame:0
          TX packets:98640 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:10 
          RX bytes:696942 (696.9 KB)  TX bytes:197167 (197.1 KB)

eno1      Link encap:Ethernet  HWaddr 00:0b:ab:a9:f6:ab  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:542235 errors:0 dropped:0 overruns:0 frame:0
          TX packets:345917 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:177910572 (177.9 MB)  TX bytes:200793712 (200.7 MB)
          Interrupt:20 Memory:f7e00000-f7e20000 

enp3s0    Link encap:Ethernet  HWaddr 00:0b:ab:a9:f6:ac  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Memory:f7c00000-f7c1ffff 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:319258 errors:0 dropped:0 overruns:0 frame:0
          TX packets:319258 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:61119893 (61.1 MB)  TX bytes:61119893 (61.1 MB)

wlp2s0    Link encap:Ethernet  HWaddr ac:fd:ce:13:80:0d  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by tonybaltovski** [comment]
When you run `wicd-cures` can you remove ethx <whatever number is there> from wired interface box in preferences?

**Comment by wilsonn-leong** [comment]
Excuse me, I don't quite understand what you said, can you give some specific guidance?

**Comment by WshgL** [comment]
@tonybaltovski Thank you very much, the wireless network can be automatically connected. By the way, its default value is `br0`.
