### ISSUE TITLE
DeserializationError cannot deserialize: unknown error handler name 'rosmsg'

### ISSUE THREAD

**Issue by RobertWalt** [ridgeback/ridgeback_robot#29]
Hey there, I installed the ridgeback_robot package inside a docker container (ros:kinetic-robot) on the ridgeback. Since last week a new error occurs, when launching base.launch in ridgeback_base. Since then /odom is not published to anymore.
The container runs in network mode host and has /dev/ attached.
Seems like the error is spreading:
https://github.com/husky/husky/issues/139
https://github.com/husky/husky/issues/142

Same error appears when running the two nodes rosserial_message_info and ridgeback_node. The rosserial_message_info node prints this error.

Please find the complete terminal output below:

> root@CPR-R100-0067:~/catkin_ws# roslaunch ridgeback_base base.launch 
> ... logging to /root/.ros/log/d418dd30-ed2b-11ea-a1fe-c400ad2eb4f6/roslaunch-CPR-R100-0067-1055.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> inconsistent namespace redefinitions for xmlns:xacro:
>  old: http://ros.org/wiki/xacro
>  new: http://www.ros.org/wiki/xacro (/opt/ros/kinetic/share/lms1xx/urdf/sick_lms1xx.urdf.xacro)
> inconsistent namespace redefinitions for xmlns:xacro:
>  old: http://ros.org/wiki/xacro
>  new: http://www.ros.org/wiki/xacro (/opt/ros/kinetic/share/lms1xx/urdf/sick_lms1xx.urdf.xacro)
> started roslaunch server http://192.168.131.1:42397/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /bluetooth_teleop/joy_node/autorepeat_rate: 20
>  * /bluetooth_teleop/joy_node/deadzone: 0.1
>  * /bluetooth_teleop/joy_node/dev: /dev/input/ds4x
>  * /bluetooth_teleop/teleop_twist_joy/axis_angular/yaw: 3
>  * /bluetooth_teleop/teleop_twist_joy/axis_linear/x: 1
>  * /bluetooth_teleop/teleop_twist_joy/axis_linear/y: 0
>  * /bluetooth_teleop/teleop_twist_joy/enable_button: 4
>  * /bluetooth_teleop/teleop_twist_joy/enable_turbo_button: 5
>  * /bluetooth_teleop/teleop_twist_joy/scale_angular/yaw: 0.5
>  * /bluetooth_teleop/teleop_twist_joy/scale_linear/x: 0.4
>  * /bluetooth_teleop/teleop_twist_joy/scale_linear/y: 0.4
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/general/expected: ['ridgeback_node:...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/general/path: General
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/general/remove_prefix: ridgeback_node
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/general/timeout: 5.0
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/general/type: diagnostic_aggreg...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/motors/expected: ['ridgeback_node:...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/motors/path: Motors
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/motors/remove_prefix: ridgeback_node
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/motors/timeout: 5.0
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/motors/type: diagnostic_aggreg...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/sensors/expected: ['ridgeback_node:...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/sensors/path: Sensor Topics
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/sensors/remove_prefix: ridgeback_node
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/sensors/timeout: 5.0
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/sensors/type: diagnostic_aggreg...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/teleop/expected: ['bluetooth_teleo...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/teleop/path: Bluetooth Joystick
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/teleop/remove_prefix: bluetooth_teleop/...
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/teleop/timeout: 5.0
>  * /diagnostic_aggregator/analyzers/ridgeback/analyzers/teleop/type: diagnostic_aggreg...
>  * /diagnostic_aggregator/analyzers/ridgeback/path: Ridgeback Base
>  * /diagnostic_aggregator/analyzers/ridgeback/type: diagnostic_aggreg...
>  * /ekf_localization/base_link_frame: base_link
>  * /ekf_localization/frequency: 50
>  * /ekf_localization/imu0: /imu/data
>  * /ekf_localization/imu0_config: [False, False, Fa...
>  * /ekf_localization/imu0_differential: False
>  * /ekf_localization/odom0: /ridgeback_veloci...
>  * /ekf_localization/odom0_config: [False, False, Fa...
>  * /ekf_localization/odom0_differential: False
>  * /ekf_localization/odom_frame: odom
>  * /ekf_localization/two_d_mode: True
>  * /ekf_localization/world_frame: odom
>  * /imu_filter/gain: 0.1
>  * /imu_filter/mag_bias_x: 0
>  * /imu_filter/mag_bias_y: 0
>  * /imu_filter/mag_bias_z: 0
>  * /imu_filter/publish_tf: False
>  * /imu_filter/use_mag: False
>  * /imu_filter/use_magnetic_field_msg: True
>  * /imu_filter/zeta: 0.001
>  * /ridgeback_joint_publisher/publish_rate: 50
>  * /ridgeback_joint_publisher/type: joint_state_contr...
>  * /ridgeback_node/use_mcu: True
>  * /ridgeback_velocity_controller/angular/z/has_acceleration_limits: True
>  * /ridgeback_velocity_controller/angular/z/has_velocity_limits: True
>  * /ridgeback_velocity_controller/angular/z/max_acceleration: 1.0
>  * /ridgeback_velocity_controller/angular/z/max_velocity: 2.0
>  * /ridgeback_velocity_controller/back_left_wheel_joint: rear_left_wheel
>  * /ridgeback_velocity_controller/back_right_wheel_joint: rear_right_wheel
>  * /ridgeback_velocity_controller/cmd_vel_timeout: 0.25
>  * /ridgeback_velocity_controller/enable_odom_tf: False
>  * /ridgeback_velocity_controller/front_left_wheel_joint: front_left_wheel
>  * /ridgeback_velocity_controller/front_right_wheel_joint: front_right_wheel
>  * /ridgeback_velocity_controller/linear/x/has_acceleration_limits: True
>  * /ridgeback_velocity_controller/linear/x/has_velocity_limits: True
>  * /ridgeback_velocity_controller/linear/x/max_acceleration: 2.5
>  * /ridgeback_velocity_controller/linear/x/max_velocity: 1.1
>  * /ridgeback_velocity_controller/linear/y/has_acceleration_limits: True
>  * /ridgeback_velocity_controller/linear/y/has_velocity_limits: True
>  * /ridgeback_velocity_controller/linear/y/max_acceleration: 2.5
>  * /ridgeback_velocity_controller/linear/y/max_velocity: 1.1
>  * /ridgeback_velocity_controller/pose_covariance_diagonal: [0.001, 0.001, 10...
>  * /ridgeback_velocity_controller/publish_rate: 50
>  * /ridgeback_velocity_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
>  * /ridgeback_velocity_controller/type: mecanum_drive_con...
>  * /ridgeback_velocity_controller/wheel_radius_multiplier: 1.0
>  * /ridgeback_velocity_controller/wheel_separation_multiplier: 1.0
>  * /ridgeback_velocity_controller/wheel_separation_x: 0.638
>  * /ridgeback_velocity_controller/wheel_separation_y: 0.551
>  * /robot_description: <?xml version="1....
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.14
>  * /twist_marker_server/linear_scale/x: 1
>  * /twist_marker_server/linear_scale/y: 1
>  * /twist_marker_server/max_negative_linear_velocity/x: -1
>  * /twist_marker_server/max_negative_linear_velocity/y: -1
>  * /twist_marker_server/max_positive_linear_velocity/x: 1
>  * /twist_marker_server/max_positive_linear_velocity/y: 1
> 
> NODES
>   /bluetooth_teleop/
>     joy_node (joy/joy_node)
>     teleop_twist_joy (teleop_twist_joy/teleop_node)
>   /
>     cmd_vel_relay (topic_tools/relay)
>     controller_spawner (controller_manager/spawner)
>     diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
>     ekf_localization (robot_localization/ekf_localization_node)
>     imu_filter (imu_filter_madgwick/imu_filter_node)
>     ridgeback_node (ridgeback_base/ridgeback_node)
>     robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     rosserial_message_info (rosserial_python/message_info_service.py)
>     twist_marker_server (interactive_marker_twist_server/marker_server)
> 
> ROS_MASTER_URI=http://192.168.131.1:11311
> 
> process[robot_state_publisher-1]: started with pid [1076]
> process[rosserial_message_info-2]: started with pid [1077]
> process[imu_filter-3]: started with pid [1103]
> process[ridgeback_node-4]: started with pid [1117]
> [ INFO] [1599060054.763210359]: rosserial_server UDP session created between 192.168.131.1:11411 and 192.168.131.2:11411
> [ INFO] [1599060054.765870373]: Dev: 5 mode set to a closed-loop control with PID gains of P:0.100000, I:0.010000 and D:0.000000.
> [ INFO] [1599060054.765925401]: Dev: 4 mode set to a closed-loop control with PID gains of P:0.100000, I:0.010000 and D:0.000000.
> [ INFO] [1599060054.765949884]: Dev: 2 mode set to a closed-loop control with PID gains of P:0.100000, I:0.010000 and D:0.000000.
> [ INFO] [1599060054.765972159]: Dev: 3 mode set to a closed-loop control with PID gains of P:0.100000, I:0.010000 and D:0.000000.
> [ INFO] [1599060054.768226718]: Opened Socket CAN on can0
> [ INFO] [1599060054.768260226]: Connection to motor driver gateway successful.
> Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 660, in handle
>     requests = transport.receive_once()
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 743, in receive_once
>     raise TransportException("receive_once[%s]: DeserializationError %s"%(self.name, str(e)))
> TransportException: receive_once[/message_info]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
> 
> [ INFO] [1599060054.809624179]: Checking for wireless connectivity on interface: wlan0
> process[controller_spawner-5]: started with pid [1167]
> [ INFO] [1599060055.468036394]: Dev: 5 all parameters verified.
> [ INFO] [1599060055.468290368]: Dev: 2 all parameters verified.
> [ INFO] [1599060055.468320595]: Dev: 3 all parameters verified.
> [ INFO] [1599060055.508023767]: Dev: 4 all parameters verified.
> [ INFO] [1599060055.547976736]: Ridgeback Hardware Active.
> Traceback (most recent call last):
>   File "/opt/ros/kinetic/lib/controller_manager/spawner", line 207, in <module>
>     if __name__ == '__main__': main()
>   File "/opt/ros/kinetic/lib/controller_manager/spawner", line 185, in main
>     resp = load_controller(name)
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
>     return self.call(*args, **kwds)
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
>     raise ServiceException("transport error completing service call: %s"%(str(e)))
> rospy.service.ServiceException: transport error completing service call: receive_once[/controller_manager/load_controller]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
> [WARN] [1599060055.668818]: Controller Spawner error while taking down controllers: transport error completing service call: receive_once[/controller_manager/switch_controller]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
> process[ekf_localization-6]: started with pid [1257]
> [controller_spawner-5] process has died [pid 1167, exit code 1, cmd /opt/ros/kinetic/lib/controller_manager/spawner ridgeback_joint_publisher ridgeback_velocity_controller __name:=controller_spawner __log:=/root/.ros/log/d418dd30-ed2b-11ea-a1fe-c400ad2eb4f6/controller_spawner-5.log].
> log file: /root/.ros/log/d418dd30-ed2b-11ea-a1fe-c400ad2eb4f6/controller_spawner-5*.log
> process[cmd_vel_relay-7]: started with pid [1279]
> process[bluetooth_teleop/joy_node-8]: started with pid [1387]
> [ERROR] [1599060056.889080637]: Couldn't open joystick /dev/input/ds4x. Will retry every second.
> process[bluetooth_teleop/teleop_twist_joy-9]: started with pid [1405]
> process[twist_marker_server-10]: started with pid [1436]
> process[diagnostic_aggregator-11]: started with pid [1463]

**Comment by civerachb-cpr** [comment]
It appears there was a bug in genpy that could cause this error.  The issue has since been resolved in genpy 0.6.13.

Can you please check if there are updates available on your system and if so, install them?

**Comment by civerachb-cpr** [comment]
It appears the issue relates to https://github.com/ros/genpy/issues/132.

**Comment by RobertWalt** [comment]
Thank you civerachb-cpr for the quick response! A `apt dist-upgrade` after all apt installs fixed this, so I believe your assumption is correct and the issue has been resolved.
